drop procedure execute_sql;
drop function does_object_exist;
drop function does_package_exist;
drop procedure drop_package;
drop function does_table_exist;
drop function does_column_exist;
drop function does_index_exist;
drop function does_constraint_exist;
drop procedure drop_index;
drop procedure drop_object;
drop procedure drop_table;
drop function does_sequence_exist;
drop procedure drop_sequence;
drop procedure create_sequence;
drop function does_scheduler_job_exist;
drop function num_get_val_from_sql;
drop function does_database_account_exist;
exec arcsql.stop;
drop package body arcsql;
drop package arcsql;
drop function arcsql_version;
drop view locked_objects;
drop view lockers;
drop view name_generator;
drop view lock_time;
drop table cache;
drop table arcsql_config;
drop sequence seq_sql_log_id;
drop table sql_snap;
drop table sql_log;
drop table sql_log_arc;
drop table sql_log_active_session_history;
drop view sql_snap_view;
drop sequence seq_counter_id;
drop table arcsql_counter;
drop sequence seq_event_id;
drop table arcsql_event;
drop table audsid_event;
drop table arcsql_event_log;
drop sequence seq_version_update_id;
drop table app_version cascade constraints purge;
drop table arcsql_log_type cascade constraints purge;
drop sequence seq_arcsql_log_entry;
drop table arcsql_log;
drop table test_profile cascade constraints purge;
drop table app_test cascade constraints purge;
drop table contact_group cascade constraints purge;
drop table arcsql_alert_priority cascade constraints purge;
drop table arcsql_alert cascade constraints purge;
drop package arcsql;
exec dbms_scheduler.drop_job('arcsql_run_sql_log_update');
exec dbms_scheduler.drop_job('arcsql_check_alerts');
exec dbms_scheduler.drop_job('arcsql_check_contact_groups');
drop package arcsql_public_settings;
