exec arcsql.stop;
drop package body arcsql;
drop package arcsql;
drop function arcsql_version;
drop view locked_objects;
drop view lockers;
drop view name_generator;
drop view lock_time;
drop table cache;
drop table config_settings;
drop sequence seq_sql_log_id;
drop table sql_snap;
drop table sql_log;
drop table sql_log_arc;
drop table sql_log_active_session_history;
drop view sql_snap_view;
drop sequence seq_counter_id;
drop table counter;
drop sequence seq_event_id;
drop table event;
drop table audsid_event;
drop sequence seq_version_update_id;
drop table app_version cascade constraints purge;
drop sequence seq_arcsql_log_entry;
drop table arcsql_log;
